from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]

PAPERS = {
"10095": dict(person="Dario Floreano", title="Evolutionary Robotics", authors="Stefano Nolfi, Josh Bongard, Phil Husbands, Dario Floreano", venue="Springer Handbook of Robotics, 2016, pp. 2035-2068", link="https://doi.org/10.1007/978-3-319-32552-1_76", tags=["Evolutionary Robotics","Neuroevolution","Morphology","Reality Gap"], tldr="这是一篇进化机器人综述：把机器人控制器、神经结构乃至身体形态编码为基因型，以任务适应度驱动种群搜索；它系统讨论了仿真到真实迁移、形态-控制协同进化、在线适应和计算神经行为学。", insight="机器人设计不必被拆成由工程师逐层指定的感知、控制和形态模块；只要定义可测的行为目标、遗传表示和环境，进化搜索可以在闭环交互中自动发现非直觉但有效的整体方案。", architecture=["任务与环境|给出适应度和交互条件","基因型|编码权重、拓扑或形态","发育/解码|生成机器人表型","闭环评估|仿真或实体运行","选择与变异|产生下一代"], task=["自动生成自主机器人的控制器、神经网络结构和身体形态。","既服务工程优化，也作为检验生物机制假说的合成方法。","评价对象是完整的感知-动作闭环，而不是孤立的监督学习误差。"], challenges=["搜索空间同时包含离散拓扑、连续参数和形态变量，维度高且适应度稀疏。","仿真中的微小误差会被进化利用，形成在实体上失效的投机策略，即 reality gap。","适应度设计容易导致行为捷径；实体评估又昂贵、慢且会磨损硬件。"], method=["用人工基因组表示控制器参数、网络连接规则或形态生成规则。","按选择-复制-变异/重组循环优化群体，并以机器人完成任务的累计表现作为适应度。","通过增量进化、模块化/间接编码、形态与大脑协同进化改善可扩展性。","采用噪声注入、多个仿真条件和少量实体复评，抑制对单一仿真器的过拟合。"], formula=r"\theta^*=\arg\max_{\theta}\;\mathbb{E}_{e\sim p(e)}[F(\pi_\theta,e)]", principles=["适应度定义选择压力，决定搜索真正优化的行为。","间接编码和发育映射能够用紧凑基因型生成规则化的大型网络或形态。","进化与个体学习可工作在不同时间尺度：前者塑造先验，后者适应快速变化。"], evidence=["章节汇总了不同尺寸、形态和运行特征的仿真与实体机器人案例。","重点比较直接/间接编码、固定/可变拓扑、控制器/形态协同进化。","作者把仿真-实体迁移作为方法成立与否的核心检验，而非附加展示。"], flaws=["综述覆盖面大，但不同案例的适应度预算和硬件条件差异很大，难以横向量化。","高维开放式进化的样本效率仍明显低于利用梯度和先验的方法。","行为可解释性与安全约束通常不是适应度的自然产物，需要额外机制。"], motivation="手工设计在高维、强耦合机器人系统中会把工程师的假设固化进结构；进化机器人希望直接从任务交互中发现控制与形态的匹配关系。", takeaways=["把设计变量扩大到结构和形态，可能比只调控制器参数获得更大的性能跃迁。","仿真随机化和实体回灌应从搜索早期介入，不能等最终部署再处理 reality gap。","适应度是隐含的需求规格；设计不当时，进化会忠实地优化错误目标。"]),
"10098": dict(person="Dario Floreano", title="Bio-Inspired Artificial Intelligence: Theories, Methods, and Technologies", authors="Dario Floreano, Claudio Mattiussi", venue="MIT Press, 2008", link="https://mitpress.mit.edu/9780262062718/bio-inspired-artificial-intelligence/", tags=["Bio-inspired AI","Self-organization","Evolution","Collective Intelligence"], tldr="本书以自组织和自适应为主线，将进化、神经网络、发育、免疫系统和群体智能转化为人工智能方法；核心不是复制生物外形，而是提炼能产生稳健智能行为的机制。", insight="生物智能并非由中央规划器逐条编程，而是从局部规则、环境反馈、学习和进化的多尺度耦合中涌现；工程上应复现这些生成原则，而非只模仿最终行为。", architecture=["生物观察|数据与理论","机制抽象|局部规则、选择、可塑性","计算模型|网络、种群、群体","人工系统|软件或机器人","实验反馈|验证工程性能与生物假说"], task=["建立生物启发式 AI 的统一概念与方法地图。","解释进化计算、神经计算、发育系统、人工免疫和群体智能。","展示智能制品如何反过来检验生物学假说。"], challenges=["生物系统跨越基因、个体和群体尺度，简单类比容易丢失关键因果机制。","涌现系统的微观规则与宏观性能之间缺少直接可解释映射。","自组织方法常以随机性换取适应性，工程验证和失效预测更困难。"], method=["从生物证据中抽取可计算的状态、局部交互和适应机制。","以进化、学习或群体交互驱动系统自组织，而非规定完整行为序列。","用人工系统复现实验现象，再比较预测与生物观测形成闭环。"], formula=r"x_i(t+1)=f\!\left(x_i(t),\,\mathcal{N}_i(t),\,e(t)\right)", principles=["自组织：全局结构由局部交互形成。","自适应：系统根据反馈改变参数或结构。","具身性：智能依赖身体、环境与控制器的闭环，而非纯符号处理。"], evidence=["书中贯通遗传算法、神经进化、群体机器人、人工免疫和发育模型。","大量实例同时承担工程原型与生物机制的合成验证。","结论强调科学抽象与工程转化必须共同进行，不能停留在生物隐喻。"], flaws=["作为 2008 年教材，未覆盖深度学习、现代基础模型与大规模离线数据范式。","跨领域统一视角可能弱化各生物机制的实验边界和统计证据差异。","涌现行为的安全验证、可复现性和计算成本仍缺少统一工程标准。"], motivation="传统 AI 常把智能拆成预定义模块，而自然系统展示了另一条路径：通过选择、学习和局部交互形成能适应未知环境的整体行为。", takeaways=["生物启发应复制机制而非外观。","设计局部交互规则时必须同步定义宏观验证指标。","机器人既是应用平台，也是检验认知与行为假说的实验工具。"]),
"10099": dict(person="Dario Floreano", title="Neuroevolution: From Architectures to Learning", authors="Dario Floreano, Peter Dürr, Claudio Mattiussi", venue="Evolutionary Intelligence 1, 47-62, 2008", link="https://doi.org/10.1007/s12065-007-0002-4", tags=["Neuroevolution","ANN","Topology Evolution","Learning Rules"], tldr="本文综述神经进化如何从仅优化固定网络权重，发展到共同搜索拓扑、神经元模型、发育编码和学习规则，并强调进化可合成“会学习的架构”。", insight="若只进化权重，搜索被人为选定的架构上限所限制；把拓扑、动力学和可塑性规则纳入基因型，进化就能在更高层次发现适合任务的学习偏置。", architecture=["基因型|权重、拓扑、神经元与可塑性","解码|构造 ANN","生命周期学习|按局部规则更新","任务评估|闭环行为适应度","进化|选择结构与学习机制"], task=["归纳人工神经网络的主要进化表示和搜索策略。","比较直接编码、增量拓扑进化与发育/生成式编码。","说明如何进化学习规则，使网络在生命周期中继续适应。"], challenges=["网络同构导致许多基因型表达同一功能，搜索冗余巨大。","拓扑改变后个体间交叉对齐困难。","同时搜索结构、权重和学习规则会形成强烈的信用分配问题。"], method=["固定拓扑方法直接编码突触权重。","拓扑与权重共同进化通过结构突变逐步复杂化网络。","间接编码用发育规则或坐标模式生成重复、模块化连接。","元学习式神经进化把 Hebbian 等局部可塑性参数写入基因组。"], formula=r"\Delta w_{ij}=\eta\,(A x_i x_j+B x_i+C x_j+D)", principles=["结构搜索改变的是模型归纳偏置，而不只是数值参数。","复杂化保护允许从简单可行行为逐步增加功能。","进化负责跨代发现学习规则，个体学习负责一生中的快速适应。"], evidence=["论文按权重、架构、神经元动力学和学习架构四个层次组织代表方法。","案例覆盖模式分类与机器人控制，突出闭环任务中梯度不可得时的价值。","作者特别讨论神经科学与进化生物学的新见解如何反哺编码设计。"], flaws=["综述早于现代深度神经架构搜索和大规模并行进化，计算结论具有时代边界。","基准规模较小，很多方法在深网络上的预算与稳定性尚未验证。","复杂基因型提高表达能力的同时降低了可解释性与可复现性。"], motivation="神经网络性能依赖架构、神经元模型和学习算法，手工逐项选择会限制解空间；进化搜索提供了联合自动化设计的途径。", takeaways=["先判断任务瓶颈在权重还是结构，再决定进化变量。","需要把基因型的可搜索性与表型的表达能力同时设计。","进化学习规则是一种早期元学习范式，对持续适应仍有启发。"]),
"10100": dict(person="Dario Floreano", title="Generating Realistic In Silico Gene Networks for Performance Assessment of Reverse Engineering Methods", authors="Daniel Marbach, Thomas Schaffter, Claudio Mattiussi, Dario Floreano", venue="Journal of Computational Biology 16(2), 229-239, 2009", link="https://doi.org/10.1089/cmb.2008.09TT", tags=["Gene Regulatory Networks","DREAM","Benchmark","Network Motifs"], tldr="本文不再用随机图充当基因网络真值，而是从已知酵母调控网络抽取保留功能与结构性质的模块，再生成动力学数据，为 DREAM 反向工程算法提供更真实的 gold-standard 基准。", insight="网络推断算法的排名高度依赖测试图的拓扑与动力学生成过程；若模拟网络缺少真实生物网络的模块、motif 和度分布，基准会奖励只适合随机图的方法。", architecture=["已知生物网络|酵母调控图","模块抽取|保留局部连接模式","动力学模型|调控函数与参数","扰动实验|稳态/时间序列数据","推断评测|与隐藏 gold standard 比较"], task=["生成具有生物合理结构的 in silico 基因调控网络。","为网络反向工程算法提供已知真值且可重复的评测数据。","检验抽取模块是否保留原网络的功能和结构特性。"], challenges=["真实网络真值不完整，不能直接作为无偏评测标签。","随机图只部分复现生物网络拓扑。","结构真实并不自动保证表达动力学和实验噪声真实。"], method=["从酵母转录调控网络中抽取连通子模块，而非从随机图采样。","比较模块的连接度、网络 motif 和功能一致性。","在模块上定义可控动力学并产生扰动数据。","以隐藏边集为 gold standard 计算推断算法的精确率-召回率与 ROC 表现。"], formula=r"\dot{x}_i=f_i(x_1,\ldots,x_n)-\lambda_i x_i+\epsilon_i(t)", principles=["基准有效性取决于数据生成分布与真实任务分布的接近程度。","结构真值与观测动力学应分开控制。","模块抽取在可验证规模和生物真实性之间提供折中。"], evidence=["酵母网络模块保留了原网络的功能与结构属性。","该方法被用于 DREAM3 基因网络反向工程挑战的 gold-standard 网络。","与随机图相比，抽取模块能更现实地暴露推断算法的强弱。"], flaws=["从已知网络抽取会继承原始数据库的漏边和研究偏差。","单一酵母网络不代表不同物种、细胞类型和调控层级。","简化动力学仍未覆盖染色质、翻译后调控与细胞异质性。"], motivation="网络推断方法通常先在模拟数据上验证，但不真实的随机网络会产生虚假的性能信心，因此需要兼具已知真值和生物结构的测试系统。", takeaways=["评估算法前先审查基准生成过程是否代表部署分布。","公开隐藏真值、扰动协议和噪声模型，才能让比较可复现。","真实模块比全随机图更适合作为结构推断压力测试。"]),
"10101": dict(person="Dario Floreano", title="Swarmanoid: A Novel Concept for the Study of Heterogeneous Robotic Swarms", authors="Marco Dorigo et al.", venue="IEEE Robotics & Automation Magazine 20(4), 60-71, 2013", link="https://doi.org/10.1109/MRA.2013.2252996", tags=["Swarmanoid","Heterogeneous Swarm","Self-assembly","Collective Robotics"], tldr="Swarmanoid 以 foot-bot、hand-bot 和 eye-bot 三类机器人组成异构群体，分别承担地面运输、攀爬抓取和空中观测，通过物理/行为协作完成单一类型机器人无法完成的 3D 搜索取物任务。", insight="异构群体的价值不是简单叠加不同机器人，而是让每种形态承担与其物理能力匹配的角色，并通过局部交互形成跨空中、地面和垂直表面的集体能力。", architecture=["eye-bot|空中搜索与全局观测","foot-bot|地面移动、运输与协同","hand-bot|攀爬和抓取","局部通信与信标|任务协调","群体任务|搜索、获取并运送目标"], task=["提出可研究异构群体机器人的 Swarmanoid 概念与硬件平台。","验证三种机器人能否协同完成高处物体搜索、抓取和运输。","识别异构群体在硬件集成、控制和实验方法上的关键挑战。"], challenges=["机器人具有不同运动空间、传感器和通信能力。","hand-bot 的垂直机动依赖 foot-bot 运输和攀爬界面。","中心化规划会削弱群体鲁棒性，但纯局部决策增加跨角色协调难度。"], method=["eye-bot 在空中定位目标并提供环境信息。","foot-bot 自组织聚集、运输 hand-bot，并在地面形成移动群体。","hand-bot 利用磁性/机械装置攀爬、抓取目标，再由群体运回。","采用分布式行为与局部通信连接角色专长。"], formula=r"\Pi=\{\pi_{eye},\pi_{foot},\pi_{hand}\},\quad J=J(\Pi,\mathcal{E})", principles=["功能异构使任务分解落在物理能力而非抽象软件模块上。","群体鲁棒性来自冗余个体和去中心化协作。","身体接口与控制协议必须协同设计。"], evidence=["平台完成了三维环境中的目标搜索、攀爬获取和地面运输演示。","论文展示三类机器人之间的行为和物理交互。","总结指出紧密集成的异构硬件是该领域最主要的研究门槛之一。"], flaws=["演示依赖专门设计的硬件接口和受控环境，外部有效性有限。","三类平台的制造与维护成本削弱了大规模冗余优势。","成功展示证明可行性，但缺少与同质群体或中心化系统的统一量化对照。"], motivation="同质机器人群体受单体物理能力限制；现实任务往往同时需要飞行观测、地面运输和垂直操作，因此必须研究跨形态的群体协作。", takeaways=["异构系统应按不可替代的物理能力划分角色。","通信协议之外，机械连接和可运输性也是群体接口。","评价异构群体时应同时报告任务收益与系统复杂度成本。"]),
"10102": dict(person="Dario Floreano", title="Swarm-bot: A New Distributed Robotic Concept", authors="Francesco Mondada et al.", venue="Autonomous Robots 17, 193-221, 2004", link="https://doi.org/10.1023/B:AURO.0000033972.50769.1F", tags=["Swarm-bot","Self-assembly","Distributed Robotics","Physics Simulation"], tldr="Swarm-bot 把群体智能从控制层扩展到物理层：多个可自主移动的 s-bot 能连接成具备协同牵引和越障能力的实体结构；论文同时给出硬件、电子、软件和经实体标定的 swarmbot3d 仿真器。", insight="当单机器人受牵引力、稳定性或地形通过性限制时，群体不应只交换信息，还可动态改变物理拓扑，把多个弱个体组装成一个可重构的强实体。", architecture=["s-bot 个体|移动、感知与抓接","自组装接口|连接/断开","swarm-bot|物理聚合结构","分布式控制|局部协调牵引","swarmbot3d|设计与控制快速评估"], task=["设计能自组装的群体机器人概念及 s-bot 实体。","构建物理仿真器以快速评估硬件选项和分布式算法。","校准仿真，使单个 s-bot 的动力学行为匹配实体。"], challenges=["连接机构必须可靠，同时不能妨碍单体移动。","连接后各轮式机器人受力耦合，局部动作容易互相抵消。","复杂地形中的接触和摩擦很难准确模拟。"], method=["为 s-bot 配置移动底盘、环形抓接机构、传感器和局部通信。","允许个体在独立探索与物理连接模式间切换。","在 swarmbot3d 中建立刚体、接触和执行器模型。","用真实 s-bot 实验标定详细模型，支撑控制器迁移。"], formula=r"m_i\ddot{q}_i=u_i+\sum_{j\in\mathcal{N}_i}f_{ij}+f_{env}", principles=["物理自组装把网络拓扑变成可控制的机械变量。","局部连接力构成隐式通信通道。","高保真仿真需以实体系统辨识和行为对齐为依据。"], evidence=["论文报告了从 2001 年起的硬件和软件集成成果。","单 s-bot 详细仿真经实体行为标定。","系统面向极端地形探索等单体无法完成的任务。"], flaws=["论文阶段的完整 35 机器人群体仍属建设目标，系统级证据有限。","仿真校准主要针对单体，连接群体的接触误差可能累积。","专用连接硬件增加重量、能耗和故障模式。"], motivation="传统群体机器人只在信息和行为层协作，无法突破单体的物理能力上限；极端地形需要机器人通过连接形成新的整体结构。", takeaways=["将“是否连接”视为高层动作，可让群体同时拥有分散探索和聚合越障两种模式。","仿真器必须用实体数据标定，尤其是接触、摩擦与执行器饱和。","机械、电气和控制共同决定自组装系统是否可用。"]),
"10103": dict(person="Dario Floreano", title="Evolving Self-Organizing Behaviors for a Swarm-bot", authors="Marco Dorigo et al.", venue="Autonomous Robots 17, 223-245, 2004", link="https://doi.org/10.1023/B:AURO.0000033973.24945.f3", tags=["Evolutionary Swarm Robotics","Aggregation","Coordinated Motion","Scalability"], tldr="本文用人工进化合成 swarm-bot 的聚集与连接后协调运动控制器；简化物理仿真实验表明，局部感知-动作规则能涌现可扩展、可泛化的群体行为，并在经实体校准的详细模型上测试可迁移性。", insight="不必显式指定每个 s-bot 的角色和编队轨迹；只优化群体级任务结果，进化可发现利用局部传感、连接力和邻居交互的简单控制器，从而产生协调的整体运动。", architecture=["局部传感|邻居、光源与连接状态","神经控制器|个体共享参数","s-bot 动作|轮速与连接行为","群体动力学|聚集/协调运动","进化评估|群体级适应度"], task=["自动合成 swarm-bot 的聚集控制器。","让已连接的多个 s-bot 协调运动到目标。","检验控制器对更大群体和新初始构型的扩展与泛化。"], challenges=["个体只能获得局部信息，却要优化群体级目标。","连接后的执行器可能产生冲突力和原地僵持。","仿真中进化出的策略可能依赖不真实的接触细节。"], method=["所有 s-bot 共享同一神经控制器，保持同质和可扩展。","在物理仿真中以聚集程度、移动速度/方向等群体指标计算适应度。","通过种群选择和突变搜索控制器参数。","在未见群体规模、不同构型和更详细的校准仿真中复测。"], formula=r"F=\alpha\,C_{aggregate}+\beta\,V_{group}-\gamma\,E_{conflict}", principles=["参数共享把群体规模从模型输入中解耦。","局部规则通过物理耦合产生宏观有序行为。","泛化必须跨初始条件、群体规模和仿真精度检验。"], evidence=["进化发现了简单但有效的聚集与协调运动控制器。","控制器在大于训练规模的群体上仍能工作。","在不同初始构型上产生相似行为，并用详细模型评估实体可迁移性。"], flaws=["适应度由研究者设定，可能排除未预期但重要的行为质量。","详细仿真验证仍不等同于大规模实体群体实验。","聚集和定向移动是基础原语，距离复杂任务链仍有差距。"], motivation="swarm-bot 的机械耦合使解析建模和手工控制极其困难，适合用进化在闭环仿真中直接搜索能自组织的局部规则。", takeaways=["群体控制器应优先共享参数并只依赖局部可测量量。","训练成功后要主动扩大群体规模和扰动初始构型。","物理相互作用既是控制难点，也可成为涌现协调的资源。"]),
"10049": dict(person="Tairan He", title="Learning Human-to-Humanoid Real-Time Whole-Body Teleoperation", authors="Tairan He, Zhengyi Luo, Wenli Xiao et al.", venue="IEEE/RSJ IROS, 2024, pp. 8944-8951", link="https://doi.org/10.1109/IROS58592.2024.10801984", tags=["H2O","Humanoid","Teleoperation","Sim-to-real"], tldr="H2O 用单个 RGB 相机实现全尺寸人形机器人的实时全身遥操作：先以 privileged motion imitator 进行 sim-to-data 可行运动筛选，再训练鲁棒运动模仿策略并零样本迁移到实体。", insight="人类动作数据不能直接作为机器人控制参考；先让一个拥有特权状态的仿真控制器充当“可行性过滤器”，把动作库投影到机器人可实现流形，再训练面向部署的实时策略，可同时解决数据规模与动力学可行性。", architecture=["RGB 视频|3D 人体姿态估计","动作重定向|映射到机器人骨架","sim-to-data|特权模仿器筛选/修正","部署策略|本体感知+目标姿态","实体人形|零样本 sim-to-real"], task=["仅用 RGB 相机实时遥操作全尺寸人形机器人。","跟踪行走、后跳、踢腿、转身、挥手、推和拳击等动态全身动作。","构造大规模、对真实机器人可执行的重定向动作数据。"], challenges=["人和机器人的比例、关节自由度、限位与动力学不同。","单目姿态估计含遮挡、深度歧义和抖动。","动态动作涉及接触切换与平衡，误差会迅速导致跌倒。"], method=["将人体动作重定向至机器人关节空间。","训练可访问完整仿真状态的 privileged motion imitator。","用该控制器执行并筛除不可行运动，形成 sim-to-data 数据。","以域随机化训练只依赖可部署观测的鲁棒模仿策略。","在线接收视觉姿态目标并在真实机器人上零样本执行。"], formula=r"r_t=w_p r_{pose}+w_v r_{vel}+w_e r_{ee}+w_b r_{balance}", principles=["动作重定向解决几何对应，动力学模仿解决可执行性，两者不可混为一层。","特权教师可在训练时利用仿真真值，学生策略必须只依赖部署可得信号。","域随机化用参数分布训练抵抗质量、延迟与地面接触误差。"], evidence=["论文声称首次展示学习式实时全身人形遥操作。","实体演示覆盖走、跳、踢、转身、挥手、推和拳击等动作。","系统只需 RGB 相机作为操作员侧感知，并实现零样本实体迁移。"], flaws=["单目人体姿态错误会直接转化为控制目标，缺少显式置信度门控。","演示偏运动技能，精细手部操作与强环境接触仍未覆盖。","动作可行性筛选可能丢弃困难但可通过更好控制器实现的样本。"], motivation="全自主机器人仍难完成复杂开放任务，而传统遥操作依赖外骨骼、力传感或昂贵动捕；人形形态与人体相近，使低成本视觉全身遥操作成为可扩展的数据和控制接口。", takeaways=["先用仿真教师把互联网/人体动作变成机器人可执行数据。","把视觉估计与低层稳定控制解耦可提高系统容错。","遥操作系统还能成为后续模仿学习的数据采集器。"]),
"10052": dict(person="Tairan He", title="HOVER: Versatile Neural Whole-Body Controller for Humanoid Robots", authors="Tairan He et al.", venue="arXiv:2410.21229v2, 2025", link="https://arxiv.org/abs/2410.21229", tags=["HOVER","Humanoid","Multi-mode Control","Policy Distillation"], tldr="HOVER 把全身运动模仿视为导航、遥操作、局部关节跟踪等控制模式的公共抽象，并通过多模式策略蒸馏将不同教师统一为一个可用掩码指定控制部位与命令类型的策略。", insight="多种人形控制接口表面上命令空间不同，本质上都约束完整运动轨迹的某些子集；用运动学掩码表达“哪些量被命令”，可把模式切换转化为条件化部分跟踪问题。", architecture=["多类接口|VR、RGB、动捕、摇杆","统一命令|关节/末端/根部目标","运动学掩码|指定受控子空间","多教师策略|各模式专家","HOVER 学生|统一多模式控制"], task=["用单一策略覆盖导航、全身遥操作、上身控制和局部关节控制。","无需为每种命令空间重新训练策略。","在运行时平滑切换控制模式并保留各专家优势。"], challenges=["不同模式的观测、目标维度和时间尺度差异大。","联合训练会发生梯度冲突和模式遗忘。","未被命令的身体部位仍需保持平衡并产生自然补偿动作。"], method=["把全身运动模仿作为共同技能底座。","用位置、局部关节角和根部运动三类跟踪目标构造统一命令。","使用 kinematic mask 指示当前被约束的身体量。","由多个专用教师产生动作或价值监督，再蒸馏至统一学生。","训练中随机化模式与掩码，使策略学习缺省全身协调。"], formula=r"\mathcal{L}_{distill}=\mathbb{E}\left[\|\pi_{HOVER}(o,c,m)-a_{teacher}\|^2\right]", principles=["部分观测命令可统一表示为完整运动状态上的掩码约束。","蒸馏将多个专家的互补能力压缩进共享策略。","未受控自由度不是零输出，而应由策略用于稳定和协调。"], evidence=["论文展示多种控制接口映射到统一多模式命令空间。","HOVER 可在不同模式之间无缝切换。","统一策略避免每新增一种控制接口都重新训练低层控制器。"], flaws=["蒸馏上限受教师质量和训练模式覆盖范围限制。","掩码组合数量呈指数增长，未见组合的可靠性仍需验证。","模式切换的安全边界和最坏情况稳定性缺少形式化保证。"], motivation="人形机器人应用需要根速度、末端姿态、上身关节或全身姿态等不同接口；逐模式训练策略成本高、难维护，也阻碍任务之间复用。", takeaways=["先寻找跨任务公共动作抽象，再设计统一接口。","显式掩码比为每种模式增加独立网络更易扩展。","评测应包含模式切换瞬间，而不仅是每种模式的稳态性能。"]),
"10057": dict(person="Tairan He", title="Safety Index Synthesis via Sum-of-Squares Programming", authors="Weiye Zhao, Tairan He, Changliu Liu", venue="American Control Conference, 2023", link="https://arxiv.org/abs/2209.09134", tags=["Safety Index","Sum-of-Squares","Safe Control","Robotics"], tldr="本文把受输入限制系统的安全指标设计转化为安全边界上的局部流形正性条件，并借助 Positivstellensatz 与 SOS 规划自动合成安全指标；相比要求全状态空间正性的方法更不保守且可扩展。", insight="保证安全控制存在并不需要在整个状态空间施加强正性条件；真正关键的是安全集边界上至少存在一个受限控制能让系统指向安全侧。把全局条件缩到边界流形，显著降低保守性。", architecture=["系统与输入界|多项式动力学","参数化安全指标|定义安全集","边界可行性|局部流形正性","Positivstellensatz|SOS 证书","非线性优化|求解指标参数"], task=["在控制输入受限时自动合成安全指标函数。","确保安全边界上安全控制集合非空。","扩展到高自由度机械臂和地面车辆。"], challenges=["安全函数梯度与受限动力学耦合，手工设计依赖专家经验。","全局正性条件过强，常导致本来可行的问题无解。","高维 SOS 半定规划的规模增长快。"], method=["定义安全集为 φ(x)≤0，并要求边界 φ(x)=0 上存在允许控制使 φ̇<0。","消去有界控制选择后，把可行性写成边界流形上的正性问题。","利用实代数几何 Positivstellensatz 构造 SOS 证书。","联合优化安全指标参数和 SOS 乘子，并用现成求解器计算。"], formula=r"\mathcal{U}_{safe}(x)=\{u\in\mathcal{U}:\dot\phi(x,u)\le -\eta\},\quad x\in\{\phi=0\}", principles=["前向不变性：边界向量场指向集合内部即可保持安全。","SOS 多项式提供全局非负性的可计算充分证书。","局部流形约束比全空间约束更贴合安全所需条件。"], evidence=["在不同自由度机械臂和地面车辆上验证。","合成指标保证安全控制存在，并在高维机器人系统上保持可求解。","实验显示局部流形条件比既有全局正性方法更不保守。"], flaws=["SOS 证书是充分非必要条件，仍可能遗漏有效的非 SOS 安全指标。","依赖多项式或可多项式化的动力学描述。","非线性 SOS 联合优化可能受初始化影响，且高维规模仍昂贵。"], motivation="安全索引能把安全要求转化为实时控制约束，但受输入限幅时如何设计一个始终存在可行安全动作的指标，长期依赖手工经验。", takeaways=["安全证明应只在真正决定不变性的边界上施加条件。","先证明安全动作非空，再讨论性能控制器如何投影。","自动合成可减少专家调参，但必须报告求解规模和证书保守性。"]),
"10058": dict(person="Tairan He", title="Probabilistic Safeguard for Reinforcement Learning Using Safety Index Guided Gaussian Process Models", authors="Weiye Zhao, Tairan He, Rui Chen, Changliu Liu", venue="Learning for Dynamics and Control Conference, 2023", link="https://proceedings.mlr.press/v211/zhao23a.html", tags=["Safe RL","Gaussian Process","Safety Index","Forward Invariance"], tldr="本文用安全指标指导高斯过程动力学学习与离线采样，构建可包裹任意 RL 策略的安全过滤器；在输入限幅下保证安全动作非空，并给出概率前向不变性保证，Safety Gym 等仿真中接近零违规。", insight="安全模型学习不应只追求全局预测误差最小，而应把数据预算集中到决定安全控制可行性的边界区域；用 GP 不确定性修正安全约束，才能把模型置信度转化为概率安全保证。", architecture=["离线安全数据|按安全需求选点","Gaussian Process|学习未知动力学","安全指标|定义安全集与方向","安全过滤器|修正 RL 动作","受控系统|概率前向不变"], task=["在没有白盒或既有黑盒动力学模型时保护任意 RL agent。","持续满足硬状态约束，而非只降低平均违规成本。","在控制限幅下给出概率安全保证。"], challenges=["RL 的试错过程本身可能访问危险状态。","学习模型在安全边界附近的小误差会改变动作可行性判断。","有限离线数据无法均匀覆盖高维状态空间。"], method=["依据安全边界和控制可行性构造离线动力学数据集。","用 GP 学习动力学均值与方差。","设计满足输入限制的安全指标，保证安全动作集合非空。","把 GP 置信区间加入 φ̇ 约束，形成不确定性感知安全集。","在线将 RL 建议动作投影/修正为最近的安全动作。"], formula=r"\Pr\!\left[\dot\phi(x,u)\le -\eta\right]\ge 1-\delta,\quad u=\arg\min_{v\in\mathcal{U}_{safe}}\|v-u_{RL}\|^2", principles=["概率前向不变性把模型置信区间与集合安全连接起来。","安全过滤器与任务策略解耦，因此可以包裹不同 RL 算法。","安全导向采样关注边界可行性，而非全局均方误差。"], evidence=["机器人臂与 Safety Gym 连续控制实验中实现近零安全违规。","理论同时覆盖安全控制非空和概率前向不变性。","作者明确给出基于安全需求的离线数据构造规则。"], flaws=["离线合成采用状态空间网格离散，高维时计算昂贵。","GP 的计算与校准会随样本数和非平稳动力学恶化。","保证依赖置信区间覆盖真实动力学；核函数失配时概率含义可能不可靠。"], motivation="约束 RL 通常只能控制期望成本，无法保证训练和部署过程始终不越过硬安全边界；模型式安全控制有保证，却常假设已知动力学。", takeaways=["把安全层设计成与任务策略无关的可复用接口。","采样点应围绕安全证书的敏感区域分配。","报告“近零违规”时还应同时验证 GP 置信区间校准与离散化误差。"]),
}

CSS = """
:root{--bg:#f8fafc;--surface:#fff;--border:#e2e8f0;--text:#172033;--muted:#64748b;--blue:#2563eb;--green:#059669;--amber:#d97706;--purple:#7c3aed}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans SC',sans-serif;line-height:1.72}nav{position:sticky;top:0;z-index:5;display:flex;gap:5px;align-items:center;flex-wrap:wrap;padding:10px 22px;background:#fffffff2;border-bottom:1px solid var(--border);backdrop-filter:blur(12px)}nav a{font-size:12px;color:#475569;text-decoration:none;padding:5px 8px;border-radius:5px}nav a:hover{background:#dbeafe;color:#1d4ed8}.home{font-weight:800!important;color:#ea580c!important;border:1px solid #fb923c}.brand{font-weight:800;margin:0 8px}.wrap{max-width:1080px;margin:auto;padding:28px 20px 60px}section{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:28px;margin-bottom:20px;box-shadow:0 1px 3px #0000000a;scroll-margin-top:58px}h1{font-size:25px;line-height:1.35;margin:0 0 8px}h2{font-size:18px;margin:0 0 18px}h3{font-size:15px;margin:20px 0 8px}p,li,td,th{font-size:14px}ul,ol{padding-left:22px}.meta{color:var(--muted);font-size:13px}.tags{margin-top:12px}.tag{display:inline-block;margin:3px 5px 3px 0;padding:2px 9px;border-radius:99px;background:#dbeafe;color:#1d4ed8;font-size:11px;font-weight:700}.callout{border-left:4px solid var(--purple);background:#f5f3ff;padding:14px 18px;border-radius:0 8px 8px 0}.info{border-color:var(--blue);background:#eff6ff}.tip{border-color:var(--green);background:#ecfdf5}.warn{border-color:var(--amber);background:#fffbeb}.mermaid-box{overflow:auto;background:#fafafa;border:1px solid var(--border);border-radius:9px;padding:15px;text-align:center}.formula{overflow:auto;background:#f8fafc;border:1px solid var(--border);border-radius:8px;padding:15px 18px;margin:12px 0}table{width:100%;border-collapse:collapse}th,td{padding:9px 11px;border:1px solid var(--border);text-align:left;vertical-align:top}th{background:#f1f5f9}footer{text-align:center;color:#94a3b8;font-size:12px;padding:12px}.source{color:#475569;font-size:12px;border-top:1px dashed var(--border);padding-top:12px;margin-top:18px}@media(max-width:650px){section{padding:20px}nav{position:static}.wrap{padding:18px 10px}}
"""

def lis(items): return "<ul>"+"".join(f"<li>{x}</li>" for x in items)+"</ul>"

def diagram(nodes):
    lines=["flowchart LR"]
    for i,node in enumerate(nodes):
        title,desc=node.split("|",1)
        lines.append(f'  N{i}["{title}<br/>{desc}"]')
        if i: lines.append(f"  N{i-1} --> N{i}")
    return "\n".join(lines)

def make_note(key,p):
    tags="".join(f'<span class="tag">{escape(t)}</span>' for t in p["tags"])
    return f'''<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Paper Notes - {escape(p['title'])}</title><script>MathJax={{tex:{{inlineMath:[['$','$']],displayMath:[['$$','$$']] }},options:{{enableMenu:false}}}};</script><script async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script><script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script><script>mermaid.initialize({{startOnLoad:true,theme:'neutral',securityLevel:'loose'}});</script><style>{CSS}</style></head><body>
<nav><a class="home" href="../../index.html">🏠 SCHOLAR</a><span class="brand">Paper Notes</span><a href="#info">Info</a><a href="#insight">Insight</a><a href="#architecture">Architecture</a><a href="#task">Task</a><a href="#challenge">Challenge</a><a href="#method">Method</a><a href="#principles">Principles</a><a href="#evidence">Evidence</a><a href="#flaw">Flaw</a><a href="#motivation">Motivation</a><a href="#takeaway">Takeaways</a></nav><main class="wrap">
<section id="info"><h1>{escape(p['title'])}</h1><div class="meta">{escape(p['authors'])} · {escape(p['venue'])}</div><div class="tags">{tags}</div><h3>TL;DR</h3><div class="callout info">{p['tldr']}</div><p class="source">本笔记依据本目录 PDF 全文整理。论文入口：<a target="_blank" href="{p['link']}">{p['link']}</a></p></section>
<section id="insight"><h2>2. Insight &amp; Novelty</h2><h3>核心洞察</h3><div class="callout">{p['insight']}</div><h3>创新的逻辑</h3>{lis([p['challenges'][0],p['method'][0],p['evidence'][0]])}</section>
<section id="architecture"><h2>3. System / Argument Architecture</h2><div class="mermaid-box"><div class="mermaid">{diagram(p['architecture'])}</div></div><p>这条链路按论文中的问题设定、核心模块和评价闭环重构；对综述/书籍类文献，它表示论证框架而非单一软件管线。</p></section>
<section id="task"><h2>4. Task - 解决什么问题？</h2>{lis(p['task'])}</section>
<section id="challenge"><h2>5. Challenge - 为什么困难？</h2>{lis(p['challenges'])}</section>
<section id="method"><h2>6. Method &amp; Key Formulas</h2>{lis(p['method'])}<div class="formula">$${p['formula']}$$</div><p class="meta">公式用于概括论文的核心约束或优化关系；符号按本节语义解释，不替代原文完整推导。</p></section>
<section id="principles"><h2>7. Fundamental Principles</h2>{lis(p['principles'])}</section>
<section id="evidence"><h2>8. Evidence &amp; Results</h2><table><tr><th>证据</th><th>支持的结论</th></tr>{''.join(f'<tr><td>{i+1}</td><td>{x}</td></tr>' for i,x in enumerate(p['evidence']))}</table><div class="callout info">阅读图表时应回到同目录 PDF 核对实验设置、坐标轴和统计口径；本页不复制受版权保护的论文原图。</div></section>
<section id="flaw"><h2>9. Potential Flaw &amp; Limitations</h2>{lis(p['flaws'])}<div class="callout warn">这些限制区分了“论文已经证明的范围”和“可合理外推的范围”，不把作者未验证的场景写成既定事实。</div></section>
<section id="motivation"><h2>10. Motivation</h2><div class="callout info">{p['motivation']}</div><h3>从第一性问题到方案</h3><ol><li>确认现有方案的结构性瓶颈，而非只看单个指标。</li><li>找到能直接改变该瓶颈的表示、约束或系统接口。</li><li>用论文的实验或案例验证关键因果链，并明确未覆盖边界。</li></ol></section>
<section id="takeaway"><h2>11. Key Takeaways</h2>{lis(p['takeaways'])}<div class="callout tip"><strong>一句话复盘：</strong> {p['tldr']}</div></section>
</main><footer>Paper Notes · {escape(p['person'])} · source-grounded from local PDF · 2026-07-22</footer></body></html>'''

def make_index(person, entries):
    cards=[]
    for key,p in entries:
        cards.append(f'<a class="card" href="files/{key}/index.html"><span>{escape(p["venue"])}</span><h2>{escape(p["title"])}</h2><p>{escape(p["tldr"])}</p></a>')
    return f'''<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(person)} - Scholar Dashboard</title><style>:root{{--bg:#0f1117;--card:#1a1d27;--text:#e5e7eb;--muted:#9ca3af;--accent:#60a5fa}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans SC',sans-serif}}header{{padding:24px 32px;border-bottom:1px solid #2d3342;background:linear-gradient(135deg,#171b27,#20263a)}}header a{{color:var(--accent);text-decoration:none}}main{{max-width:1100px;margin:auto;padding:30px 22px}}.stat{{display:inline-block;border:1px solid #303649;border-radius:9px;padding:12px 20px;margin:10px 0 24px}}.stat b{{font-size:28px;color:var(--accent)}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px}}.card{{display:block;padding:18px 20px;border:1px solid #2d3342;border-radius:10px;background:var(--card);color:inherit;text-decoration:none;transition:.2s}}.card:hover{{transform:translateY(-2px);border-color:var(--accent)}}.card span{{font-size:11px;color:var(--accent)}}.card h2{{font-size:16px;line-height:1.4}}.card p{{font-size:13px;line-height:1.65;color:var(--muted)}}footer{{text-align:center;color:#6b7280;padding:28px}}</style></head><body><header><a href="../../index.html">← Back to UAV-Survey</a><h1>👤 {escape(person)}</h1><p>Scholar Dashboard · 已添加 PDF 精读笔记</p></header><main><div class="stat"><b>{len(entries)}</b><br>Tracked Papers</div><div class="grid">{''.join(cards)}</div></main><footer>UAV-Survey · Scholar Tracking</footer></body></html>'''

for key,p in PAPERS.items():
    candidates=list((ROOT/"2.Scholar"/p["person"]/"files"/key).glob("note.html"))
    if len(candidates)!=1: raise RuntimeError(f"{key}: expected one note, got {candidates}")
    candidates[0].write_text(make_note(key,p),encoding="utf-8")

# Keep all directory pages under the single canonical index builder. This
# prevents this specialized note generator from overwriting scholar indexes.
from rebuild_scholar_indexes import main as rebuild_scholar_indexes

rebuild_scholar_indexes()
print(f"Built {len(PAPERS)} notes and refreshed all scholar indexes")
